config/routes.rb
Rails.application.routes.draw do
  resources :trees
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tree.rb
class Tree < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: %i[ show edit update destroy ]

  # GET /trees or /trees.json
  def index
    @trees = Tree.all
  end

  # GET /trees/1 or /trees/1.json
  def show
  end

  # GET /trees/new
  def new
    @tree = Tree.new
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees or /trees.json
  def create
    @tree = Tree.new(tree_params)

    respond_to do |format|
      if @tree.save
        format.html { redirect_to @tree, notice: "Tree was successfully created." }
        format.json { render :show, status: :created, location: @tree }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1 or /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to @tree, notice: "Tree was successfully updated." }
        format.json { render :show, status: :ok, location: @tree }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1 or /trees/1.json
  def destroy
    @tree.destroy!

    respond_to do |format|
      format.html { redirect_to trees_path, status: :see_other, notice: "Tree was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def tree_params
      params.expect(tree: [ :name, :x, :instagram, :youtube, :user_id, :style ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/home/index.html.erb
<div>
    <div>
        <p>Hello Sushant</p>
    </div>
</div>

<%= link_to "New Tree", new_tree_path %>
<br/>
<%= link_to "My Tree", new_tree_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Linktree" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trees/_form.html.erb
<%= form_with(model: tree) do |form| %>
  <% if tree.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
        <% tree.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :x, style: "display: block" %>
    <%= form.text_field :x %>
  </div>

  <div>
    <%= form.label :instagram, style: "display: block" %>
    <%= form.text_field :instagram %>
  </div>

  <div>
    <%= form.label :youtube, style: "display: block" %>
    <%= form.text_field :youtube %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :style, style: "display: block" %>
    <%= form.text_field :style %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trees/_tree.html.erb
<div id="<%= dom_id tree %>">
  <p>
    <strong>Name:</strong>
    <%= tree.name %>
  </p>

  <p>
    <strong>X:</strong>
    <%= tree.x %>
  </p>

  <p>
    <strong>Instagram:</strong>
    <%= tree.instagram %>
  </p>

  <p>
    <strong>Youtube:</strong>
    <%= tree.youtube %>
  </p>

  <p>
    <strong>User:</strong>
    <%= tree.user_id %>
  </p>

  <p>
    <strong>Style:</strong>
    <%= tree.style %>
  </p>

</div>

app/views/trees/edit.html.erb
<% content_for :title, "Editing tree" %>

<h1>Editing tree</h1>

<%= render "form", tree: @tree %>

<br>

<div>
  <%= link_to "Show this tree", @tree %> |
  <%= link_to "Back to trees", trees_path %>
</div>

app/views/trees/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Trees" %>

<h1>Trees</h1>

<div id="trees">
  <% @trees.each do |tree| %>
    <%= render tree %>
    <p>
      <%= link_to "Show this tree", tree %>
    </p>
  <% end %>
</div>

<%= link_to "New tree", new_tree_path %>

app/views/trees/new.html.erb
<% content_for :title, "New tree" %>

<h1>New tree</h1>

<%= render "form", tree: @tree %>

<br>

<div>
  <%= link_to "Back to trees", trees_path %>
</div>

app/views/trees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tree %>

<div>
  <%= link_to "Edit this tree", edit_tree_path(@tree) %> |
  <%= link_to "Back to trees", trees_path %>

  <%= button_to "Destroy this tree", @tree, method: :delete %>
</div>